--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NetherByte233/CustomGUI
build-by-default: true
branches:
- main
projects:
  CustomGUI:
    path: ""

     icon: "resources/icon.png"
...
